name: R Package CI with renv

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libcurl4-openssl-dev libxml2-dev libssl-dev

    - name: Restore renv environment
      run: |
        Rscript -e 'install.packages("renv")'
        Rscript -e 'renv::restore()'

    - name: Build and install package
      run: |
        R CMD build .
        R CMD INSTALL mypackage_*.tar.gz  # Replace 'mypackage' with your package name

    - name: Run R CMD check
      run: |
        R CMD check mypackage_*.tar.gz --no-manual --as-cran
